// Generated by gencpp from file gelsight_mini_ros/judging_msg.msg
// DO NOT EDIT!


#ifndef GELSIGHT_MINI_ROS_MESSAGE_JUDGING_MSG_H
#define GELSIGHT_MINI_ROS_MESSAGE_JUDGING_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gelsight_mini_ros
{
template <class ContainerAllocator>
struct judging_msg_
{
  typedef judging_msg_<ContainerAllocator> Type;

  judging_msg_()
    : header()
    , is_contact(false)
    , is_overforced(false)  {
    }
  judging_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , is_contact(false)
    , is_overforced(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _is_contact_type;
  _is_contact_type is_contact;

   typedef uint8_t _is_overforced_type;
  _is_overforced_type is_overforced;





  typedef boost::shared_ptr< ::gelsight_mini_ros::judging_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gelsight_mini_ros::judging_msg_<ContainerAllocator> const> ConstPtr;

}; // struct judging_msg_

typedef ::gelsight_mini_ros::judging_msg_<std::allocator<void> > judging_msg;

typedef boost::shared_ptr< ::gelsight_mini_ros::judging_msg > judging_msgPtr;
typedef boost::shared_ptr< ::gelsight_mini_ros::judging_msg const> judging_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gelsight_mini_ros::judging_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gelsight_mini_ros::judging_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gelsight_mini_ros::judging_msg_<ContainerAllocator1> & lhs, const ::gelsight_mini_ros::judging_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.is_contact == rhs.is_contact &&
    lhs.is_overforced == rhs.is_overforced;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gelsight_mini_ros::judging_msg_<ContainerAllocator1> & lhs, const ::gelsight_mini_ros::judging_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gelsight_mini_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gelsight_mini_ros::judging_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gelsight_mini_ros::judging_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gelsight_mini_ros::judging_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gelsight_mini_ros::judging_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gelsight_mini_ros::judging_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gelsight_mini_ros::judging_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gelsight_mini_ros::judging_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10ed4c6e740e87d5c0e7f8d06f6ac17c";
  }

  static const char* value(const ::gelsight_mini_ros::judging_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10ed4c6e740e87d5ULL;
  static const uint64_t static_value2 = 0xc0e7f8d06f6ac17cULL;
};

template<class ContainerAllocator>
struct DataType< ::gelsight_mini_ros::judging_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gelsight_mini_ros/judging_msg";
  }

  static const char* value(const ::gelsight_mini_ros::judging_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gelsight_mini_ros::judging_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# timestamp\n"
"Header header\n"
"\n"
"# contact and over-forced judgement\n"
"bool is_contact\n"
"bool is_overforced\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::gelsight_mini_ros::judging_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gelsight_mini_ros::judging_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.is_contact);
      stream.next(m.is_overforced);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct judging_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gelsight_mini_ros::judging_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gelsight_mini_ros::judging_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "is_contact: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_contact);
    s << indent << "is_overforced: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_overforced);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GELSIGHT_MINI_ROS_MESSAGE_JUDGING_MSG_H
