// Generated by gencpp from file gelsight_mini_ros/ResetMarkerTrackerRequest.msg
// DO NOT EDIT!


#ifndef GELSIGHT_MINI_ROS_MESSAGE_RESETMARKERTRACKERREQUEST_H
#define GELSIGHT_MINI_ROS_MESSAGE_RESETMARKERTRACKERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gelsight_mini_ros
{
template <class ContainerAllocator>
struct ResetMarkerTrackerRequest_
{
  typedef ResetMarkerTrackerRequest_<ContainerAllocator> Type;

  ResetMarkerTrackerRequest_()
    : flag(false)  {
    }
  ResetMarkerTrackerRequest_(const ContainerAllocator& _alloc)
    : flag(false)  {
  (void)_alloc;
    }



   typedef uint8_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetMarkerTrackerRequest_

typedef ::gelsight_mini_ros::ResetMarkerTrackerRequest_<std::allocator<void> > ResetMarkerTrackerRequest;

typedef boost::shared_ptr< ::gelsight_mini_ros::ResetMarkerTrackerRequest > ResetMarkerTrackerRequestPtr;
typedef boost::shared_ptr< ::gelsight_mini_ros::ResetMarkerTrackerRequest const> ResetMarkerTrackerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator1> & lhs, const ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.flag == rhs.flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator1> & lhs, const ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gelsight_mini_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24842bc754e0f5cc982338eca1269251";
  }

  static const char* value(const ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24842bc754e0f5ccULL;
  static const uint64_t static_value2 = 0x982338eca1269251ULL;
};

template<class ContainerAllocator>
struct DataType< ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gelsight_mini_ros/ResetMarkerTrackerRequest";
  }

  static const char* value(const ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool flag\n"
;
  }

  static const char* value(const ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetMarkerTrackerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gelsight_mini_ros::ResetMarkerTrackerRequest_<ContainerAllocator>& v)
  {
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GELSIGHT_MINI_ROS_MESSAGE_RESETMARKERTRACKERREQUEST_H
