// Generated by gencpp from file gelsight_mini_ros/ResetMarkerTrackerResponse.msg
// DO NOT EDIT!


#ifndef GELSIGHT_MINI_ROS_MESSAGE_RESETMARKERTRACKERRESPONSE_H
#define GELSIGHT_MINI_ROS_MESSAGE_RESETMARKERTRACKERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gelsight_mini_ros
{
template <class ContainerAllocator>
struct ResetMarkerTrackerResponse_
{
  typedef ResetMarkerTrackerResponse_<ContainerAllocator> Type;

  ResetMarkerTrackerResponse_()
    : success(false)  {
    }
  ResetMarkerTrackerResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResetMarkerTrackerResponse_

typedef ::gelsight_mini_ros::ResetMarkerTrackerResponse_<std::allocator<void> > ResetMarkerTrackerResponse;

typedef boost::shared_ptr< ::gelsight_mini_ros::ResetMarkerTrackerResponse > ResetMarkerTrackerResponsePtr;
typedef boost::shared_ptr< ::gelsight_mini_ros::ResetMarkerTrackerResponse const> ResetMarkerTrackerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator1> & lhs, const ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator1> & lhs, const ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gelsight_mini_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gelsight_mini_ros/ResetMarkerTrackerResponse";
  }

  static const char* value(const ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetMarkerTrackerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gelsight_mini_ros::ResetMarkerTrackerResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GELSIGHT_MINI_ROS_MESSAGE_RESETMARKERTRACKERRESPONSE_H
