set(_CATKIN_CURRENT_PACKAGE "franka_rocker_control")
set(franka_rocker_control_VERSION "0.0.0")
set(franka_rocker_control_MAINTAINER "abml <abml@todo.todo>")
set(franka_rocker_control_PACKAGE_FORMAT "2")
set(franka_rocker_control_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(franka_rocker_control_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(franka_rocker_control_BUILDTOOL_DEPENDS "catkin")
set(franka_rocker_control_BUILDTOOL_EXPORT_DEPENDS )
set(franka_rocker_control_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(franka_rocker_control_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(franka_rocker_control_TEST_DEPENDS )
set(franka_rocker_control_DOC_DEPENDS )
set(franka_rocker_control_URL_WEBSITE "")
set(franka_rocker_control_URL_BUGTRACKER "")
set(franka_rocker_control_URL_REPOSITORY "")
set(franka_rocker_control_DEPRECATED "")