set(_CATKIN_CURRENT_PACKAGE "ur_realsense_calibration")
set(ur_realsense_calibration_VERSION "0.0.0")
set(ur_realsense_calibration_MAINTAINER "abml <abml@todo.todo>")
set(ur_realsense_calibration_PACKAGE_FORMAT "2")
set(ur_realsense_calibration_BUILD_DEPENDS "roscpp" "std_msgs")
set(ur_realsense_calibration_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(ur_realsense_calibration_BUILDTOOL_DEPENDS "catkin")
set(ur_realsense_calibration_BUILDTOOL_EXPORT_DEPENDS )
set(ur_realsense_calibration_EXEC_DEPENDS "roscpp" "std_msgs")
set(ur_realsense_calibration_RUN_DEPENDS "roscpp" "std_msgs")
set(ur_realsense_calibration_TEST_DEPENDS )
set(ur_realsense_calibration_DOC_DEPENDS )
set(ur_realsense_calibration_URL_WEBSITE "")
set(ur_realsense_calibration_URL_BUGTRACKER "")
set(ur_realsense_calibration_URL_REPOSITORY "")
set(ur_realsense_calibration_DEPRECATED "")