// Generated by gencpp from file llm_grasping/RadianToAngleRequest.msg
// DO NOT EDIT!


#ifndef LLM_GRASPING_MESSAGE_RADIANTOANGLEREQUEST_H
#define LLM_GRASPING_MESSAGE_RADIANTOANGLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace llm_grasping
{
template <class ContainerAllocator>
struct RadianToAngleRequest_
{
  typedef RadianToAngleRequest_<ContainerAllocator> Type;

  RadianToAngleRequest_()
    : radian(0.0)  {
    }
  RadianToAngleRequest_(const ContainerAllocator& _alloc)
    : radian(0.0)  {
  (void)_alloc;
    }



   typedef double _radian_type;
  _radian_type radian;





  typedef boost::shared_ptr< ::llm_grasping::RadianToAngleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::llm_grasping::RadianToAngleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RadianToAngleRequest_

typedef ::llm_grasping::RadianToAngleRequest_<std::allocator<void> > RadianToAngleRequest;

typedef boost::shared_ptr< ::llm_grasping::RadianToAngleRequest > RadianToAngleRequestPtr;
typedef boost::shared_ptr< ::llm_grasping::RadianToAngleRequest const> RadianToAngleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::llm_grasping::RadianToAngleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::llm_grasping::RadianToAngleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::llm_grasping::RadianToAngleRequest_<ContainerAllocator1> & lhs, const ::llm_grasping::RadianToAngleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.radian == rhs.radian;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::llm_grasping::RadianToAngleRequest_<ContainerAllocator1> & lhs, const ::llm_grasping::RadianToAngleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace llm_grasping

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::llm_grasping::RadianToAngleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::llm_grasping::RadianToAngleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::llm_grasping::RadianToAngleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::llm_grasping::RadianToAngleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::llm_grasping::RadianToAngleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::llm_grasping::RadianToAngleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::llm_grasping::RadianToAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e9eb57682bb3c42defb75c34d25e755";
  }

  static const char* value(const ::llm_grasping::RadianToAngleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e9eb57682bb3c42ULL;
  static const uint64_t static_value2 = 0xdefb75c34d25e755ULL;
};

template<class ContainerAllocator>
struct DataType< ::llm_grasping::RadianToAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "llm_grasping/RadianToAngleRequest";
  }

  static const char* value(const ::llm_grasping::RadianToAngleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::llm_grasping::RadianToAngleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 radian\n"
;
  }

  static const char* value(const ::llm_grasping::RadianToAngleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::llm_grasping::RadianToAngleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.radian);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadianToAngleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::llm_grasping::RadianToAngleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::llm_grasping::RadianToAngleRequest_<ContainerAllocator>& v)
  {
    s << indent << "radian: ";
    Printer<double>::stream(s, indent + "  ", v.radian);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LLM_GRASPING_MESSAGE_RADIANTOANGLEREQUEST_H
