// Generated by gencpp from file llm_grasping/set_rob_fun.msg
// DO NOT EDIT!


#ifndef LLM_GRASPING_MESSAGE_SET_ROB_FUN_H
#define LLM_GRASPING_MESSAGE_SET_ROB_FUN_H

#include <ros/service_traits.h>


#include <llm_grasping/set_rob_funRequest.h>
#include <llm_grasping/set_rob_funResponse.h>


namespace llm_grasping
{

struct set_rob_fun
{

typedef set_rob_funRequest Request;
typedef set_rob_funResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_rob_fun
} // namespace llm_grasping


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::llm_grasping::set_rob_fun > {
  static const char* value()
  {
    return "02058b7d55716526fae62eb68abd6f31";
  }

  static const char* value(const ::llm_grasping::set_rob_fun&) { return value(); }
};

template<>
struct DataType< ::llm_grasping::set_rob_fun > {
  static const char* value()
  {
    return "llm_grasping/set_rob_fun";
  }

  static const char* value(const ::llm_grasping::set_rob_fun&) { return value(); }
};


// service_traits::MD5Sum< ::llm_grasping::set_rob_funRequest> should match
// service_traits::MD5Sum< ::llm_grasping::set_rob_fun >
template<>
struct MD5Sum< ::llm_grasping::set_rob_funRequest>
{
  static const char* value()
  {
    return MD5Sum< ::llm_grasping::set_rob_fun >::value();
  }
  static const char* value(const ::llm_grasping::set_rob_funRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::llm_grasping::set_rob_funRequest> should match
// service_traits::DataType< ::llm_grasping::set_rob_fun >
template<>
struct DataType< ::llm_grasping::set_rob_funRequest>
{
  static const char* value()
  {
    return DataType< ::llm_grasping::set_rob_fun >::value();
  }
  static const char* value(const ::llm_grasping::set_rob_funRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::llm_grasping::set_rob_funResponse> should match
// service_traits::MD5Sum< ::llm_grasping::set_rob_fun >
template<>
struct MD5Sum< ::llm_grasping::set_rob_funResponse>
{
  static const char* value()
  {
    return MD5Sum< ::llm_grasping::set_rob_fun >::value();
  }
  static const char* value(const ::llm_grasping::set_rob_funResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::llm_grasping::set_rob_funResponse> should match
// service_traits::DataType< ::llm_grasping::set_rob_fun >
template<>
struct DataType< ::llm_grasping::set_rob_funResponse>
{
  static const char* value()
  {
    return DataType< ::llm_grasping::set_rob_fun >::value();
  }
  static const char* value(const ::llm_grasping::set_rob_funResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LLM_GRASPING_MESSAGE_SET_ROB_FUN_H
