// Generated by gencpp from file llm_grasping/set_rob_funRequest.msg
// DO NOT EDIT!


#ifndef LLM_GRASPING_MESSAGE_SET_ROB_FUNREQUEST_H
#define LLM_GRASPING_MESSAGE_SET_ROB_FUNREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace llm_grasping
{
template <class ContainerAllocator>
struct set_rob_funRequest_
{
  typedef set_rob_funRequest_<ContainerAllocator> Type;

  set_rob_funRequest_()
    : action()  {
    }
  set_rob_funRequest_(const ContainerAllocator& _alloc)
    : action(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::llm_grasping::set_rob_funRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::llm_grasping::set_rob_funRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_rob_funRequest_

typedef ::llm_grasping::set_rob_funRequest_<std::allocator<void> > set_rob_funRequest;

typedef boost::shared_ptr< ::llm_grasping::set_rob_funRequest > set_rob_funRequestPtr;
typedef boost::shared_ptr< ::llm_grasping::set_rob_funRequest const> set_rob_funRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::llm_grasping::set_rob_funRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::llm_grasping::set_rob_funRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::llm_grasping::set_rob_funRequest_<ContainerAllocator1> & lhs, const ::llm_grasping::set_rob_funRequest_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::llm_grasping::set_rob_funRequest_<ContainerAllocator1> & lhs, const ::llm_grasping::set_rob_funRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace llm_grasping

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::llm_grasping::set_rob_funRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::llm_grasping::set_rob_funRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::llm_grasping::set_rob_funRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::llm_grasping::set_rob_funRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::llm_grasping::set_rob_funRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::llm_grasping::set_rob_funRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::llm_grasping::set_rob_funRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7757aad79fa343e61bc69ed7f1b7666d";
  }

  static const char* value(const ::llm_grasping::set_rob_funRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7757aad79fa343e6ULL;
  static const uint64_t static_value2 = 0x1bc69ed7f1b7666dULL;
};

template<class ContainerAllocator>
struct DataType< ::llm_grasping::set_rob_funRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "llm_grasping/set_rob_funRequest";
  }

  static const char* value(const ::llm_grasping::set_rob_funRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::llm_grasping::set_rob_funRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string action\n"
;
  }

  static const char* value(const ::llm_grasping::set_rob_funRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::llm_grasping::set_rob_funRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_rob_funRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::llm_grasping::set_rob_funRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::llm_grasping::set_rob_funRequest_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LLM_GRASPING_MESSAGE_SET_ROB_FUNREQUEST_H
