// Generated by gencpp from file llm_grasping/SetRobFun.msg
// DO NOT EDIT!


#ifndef LLM_GRASPING_MESSAGE_SETROBFUN_H
#define LLM_GRASPING_MESSAGE_SETROBFUN_H

#include <ros/service_traits.h>


#include <llm_grasping/SetRobFunRequest.h>
#include <llm_grasping/SetRobFunResponse.h>


namespace llm_grasping
{

struct SetRobFun
{

typedef SetRobFunRequest Request;
typedef SetRobFunResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetRobFun
} // namespace llm_grasping


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::llm_grasping::SetRobFun > {
  static const char* value()
  {
    return "02058b7d55716526fae62eb68abd6f31";
  }

  static const char* value(const ::llm_grasping::SetRobFun&) { return value(); }
};

template<>
struct DataType< ::llm_grasping::SetRobFun > {
  static const char* value()
  {
    return "llm_grasping/SetRobFun";
  }

  static const char* value(const ::llm_grasping::SetRobFun&) { return value(); }
};


// service_traits::MD5Sum< ::llm_grasping::SetRobFunRequest> should match
// service_traits::MD5Sum< ::llm_grasping::SetRobFun >
template<>
struct MD5Sum< ::llm_grasping::SetRobFunRequest>
{
  static const char* value()
  {
    return MD5Sum< ::llm_grasping::SetRobFun >::value();
  }
  static const char* value(const ::llm_grasping::SetRobFunRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::llm_grasping::SetRobFunRequest> should match
// service_traits::DataType< ::llm_grasping::SetRobFun >
template<>
struct DataType< ::llm_grasping::SetRobFunRequest>
{
  static const char* value()
  {
    return DataType< ::llm_grasping::SetRobFun >::value();
  }
  static const char* value(const ::llm_grasping::SetRobFunRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::llm_grasping::SetRobFunResponse> should match
// service_traits::MD5Sum< ::llm_grasping::SetRobFun >
template<>
struct MD5Sum< ::llm_grasping::SetRobFunResponse>
{
  static const char* value()
  {
    return MD5Sum< ::llm_grasping::SetRobFun >::value();
  }
  static const char* value(const ::llm_grasping::SetRobFunResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::llm_grasping::SetRobFunResponse> should match
// service_traits::DataType< ::llm_grasping::SetRobFun >
template<>
struct DataType< ::llm_grasping::SetRobFunResponse>
{
  static const char* value()
  {
    return DataType< ::llm_grasping::SetRobFun >::value();
  }
  static const char* value(const ::llm_grasping::SetRobFunResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LLM_GRASPING_MESSAGE_SETROBFUN_H
