set(_CATKIN_CURRENT_PACKAGE "gripper_force")
set(gripper_force_VERSION "0.0.0")
set(gripper_force_MAINTAINER "abml <abml@todo.todo>")
set(gripper_force_PACKAGE_FORMAT "2")
set(gripper_force_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(gripper_force_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(gripper_force_BUILDTOOL_DEPENDS "catkin")
set(gripper_force_BUILDTOOL_EXPORT_DEPENDS )
set(gripper_force_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(gripper_force_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(gripper_force_TEST_DEPENDS )
set(gripper_force_DOC_DEPENDS )
set(gripper_force_URL_WEBSITE "")
set(gripper_force_URL_BUGTRACKER "")
set(gripper_force_URL_REPOSITORY "")
set(gripper_force_DEPRECATED "")