set(_CATKIN_CURRENT_PACKAGE "pick-and-place")
set(pick-and-place_VERSION "0.0.0")
set(pick-and-place_MAINTAINER "abml <abml@todo.todo>")
set(pick-and-place_PACKAGE_FORMAT "2")
set(pick-and-place_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(pick-and-place_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(pick-and-place_BUILDTOOL_DEPENDS "catkin")
set(pick-and-place_BUILDTOOL_EXPORT_DEPENDS )
set(pick-and-place_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(pick-and-place_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(pick-and-place_TEST_DEPENDS )
set(pick-and-place_DOC_DEPENDS )
set(pick-and-place_URL_WEBSITE "")
set(pick-and-place_URL_BUGTRACKER "")
set(pick-and-place_URL_REPOSITORY "")
set(pick-and-place_DEPRECATED "")