(cl:defpackage gelsight_mini_ros-srv
  (:use )
  (:export
   "RESETMARKERTRACKER"
   "<RESETMARKERTRACKER-REQUEST>"
   "RESETMARKERTRACKER-REQUEST"
   "<RESETMARKERTRACKER-RESPONSE>"
   "RESETMARKERTRACKER-RESPONSE"
  ))

