set(_CATKIN_CURRENT_PACKAGE "handover")
set(handover_VERSION "0.0.0")
set(handover_MAINTAINER "abml <abml@todo.todo>")
set(handover_PACKAGE_FORMAT "2")
set(handover_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(handover_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(handover_BUILDTOOL_DEPENDS "catkin")
set(handover_BUILDTOOL_EXPORT_DEPENDS )
set(handover_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(handover_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(handover_TEST_DEPENDS )
set(handover_DOC_DEPENDS )
set(handover_URL_WEBSITE "")
set(handover_URL_BUGTRACKER "")
set(handover_URL_REPOSITORY "")
set(handover_DEPRECATED "")